version: 2
jobs:
  upload_files:
    docker:
      - image: python:3.8.2
    steps:
      - checkout
      - run: if [[ $CIRCLE_BRANCH == "master" ]] ; then  echo 'export PYTHON_API_KEY=$PYTHON_PROD_API_KEY' >> $BASH_ENV ; else echo 'export PYTHON_API_KEY=$PYTHON_DEV_API_KEY' >> $BASH_ENV ; fi
      - run: if [[ $CIRCLE_BRANCH == "master" ]] ; then  echo 'export PYTHON_USERNAME=$PYTHON_PROD_USERNAME' >> $BASH_ENV ; else echo 'export PYTHON_USERNAME=$PYTHON__DEV_USERNAME' >> $BASH_ENV ; fi
      - run: pip3 install requests --user
      - run: env
      - run: ls
      - run: python3 ./ci_scripts/upload_file.py totahbot.py totahbot.py
      - run: touch .botupdate
      - run: python3 ./ci_scripts/upload_file.py .botupdate .botupdate
workflows:
  version: 2
  upload_filess:
    jobs:
      - upload_files
