version: 2
jobs:
  upload_files:
    docker:
      - image: python:3.8.2
    environment:
       PYTHON_API_KEY: ${PYTHON_DEV_API_KEY}
       PYTHON_USERNAME: ${PYTON_DEV_USERNAME}
    steps:
      - checkout
      - run: pip3 install requests --user
      - run: env
      - run: ls
      - run: python3 ./ci_scripts/upload_file.py totahbot.py totahbot.py
      - run: touch .botupdate
      - run: python3 ./ci_scripts/upload_file.py .botupdate .botupdate
workflows:
  version: 2
  upload_filess:
    jobs:
      - upload_files
