version: 2
jobs:
  upload_files:
    docker:
      - image: python:3.8.2
    steps:
      - checkout
      - run: pip3 install requests --user
      - run: export PYTHON_API_KEY=$PYTHON_DEV_API_KEY
      - run: export PYTHON_USERNAME=$PYTON_DEV_USERNAME
      - run: pwd
      - run: ll
      - run: python3 ./ci_scripts/upload_file.py totahbot.py totahbot.py
      - run: touch .botupdate
      - run: python3 ./ci_scripts/upload_file.py .botupdate .botupdate
workflows:
  version: 2
  one_and_two:
    jobs:
      - upload_files
